# Generated by Django 3.2.4 on 2023-03-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='horario',
            field=models.CharField(default=17, max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
    ]
