# Generated by Django 3.2.4 on 2023-03-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20230306_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='horario',
            new_name='horarios',
        ),
    ]
